### ISSUE TITLE
Removing wp-pagenavi pagination from feeds

### ISSUE THREAD

**Issue by fotofio** [lesterchan/wp-pagenavi#20]
I'm having an issue with only the first page of paginated post being included within a feed.
Trying now to cobble together a workaround but nothing seems satisfactory.

Using a genesis theme that provides for simple hooks using conditionals but unsure of the syntax regarding how to terminate post pagination when that content becomes part of a feed.

what is the opposite of <code>array( 'type' => 'multipart' )</code>

And how much sense does the following make::::::::::
<code> if ( is_single() ) {

if (function_exists('wp_pagenavi')) wp_pagenavi( array( 'type' => 'multipart' ) ); 

} else {
   if ( is_feed( $feeds ) ) {
     if (function_exists('wp_pagenavi')) wp_pagenavi(); 
   } 
   }</code>

**Comment by lesterchan** [comment]
Sorry what does this has to do with the plugin? The plugin doesn't control your feed. You probably have to ask on the default WP forum as this is likely a default behaviour.
