### ISSUE TITLE
wp_get_sites() has been deprecated in 4.6

### ISSUE THREAD

**Issue by schrapel** [lesterchan/wp-pagenavi#45]
https://github.com/lesterchan/wp-pagenavi/blob/17d97c8725ba092823c9ca1906deb9a7686fe574/uninstall.php#L14

**Comment by lesterchan** [comment]
Fixed https://github.com/lesterchan/wp-pagenavi/commit/36ec0577a0f423c5e24de4acb4cb30bc7c464d7c =)

**Comment by schrapel** [comment]
@lesterchan get_sites returns a object not array so this won't work

https://github.com/lesterchan/wp-pagenavi/blob/36ec0577a0f423c5e24de4acb4cb30bc7c464d7c/uninstall.php#L18

**Comment by lesterchan** [comment]
This should do the trick d6ce21585a88f6d0ff047c8cd54e730dda6f4df9
