### ISSUE TITLE
How to get pagination to work with a WP_User_Query

### ISSUE THREAD

**Issue by yoxalld** [lesterchan/wp-pagenavi#47]
I am having an issue getting the pagination to work while using the WP_User_Query. Here is what I have that doesn't seem to be working. A couple things to note: I am using this as a custom loop on a page template. You will notice I have tried both the 'page' and 'paged' vars. Neither of them seem to work. I've got pagination working with the standard posts loop as well as with a custom post type elsewhere on this site so I know the plugin works and things are good there. Any help you can provide me would be greatly appreciated. Thanks!
``` 
$user_fields = array( 'ID', 'display_name', 'user_email' );
	//$paged = ( get_query_var('page') ) ? get_query_var('page') : 1;
	$paged = ( get_query_var('paged') ) ? get_query_var('paged') : 1;
	$args = array(
		'number' => '1',
		'role__in' => array('Subcriber', 'Editor'),
		'fields' => $user_fields,
		'paged' => $paged
	); // End Args
}
if ($args){
	$user_query = new WP_User_Query( $args );
}
 if ( ! empty( $user_query->results ) ) :
	 foreach ( $user_query->results as $user ) :
		//Display stuff
	 endforeach;
	wp_pagenavi( array( 'query' => $user_query ) ); 
endif
```

**Comment by lesterchan** [comment]
This plugin is not meant to work with User Query. It is meant for Post only
