### ISSUE TITLE
Not working if 'posts_per_page' is set in custom WP_Query

### ISSUE THREAD

**Issue by JulesAlexiu** [lesterchan/wp-pagenavi#54]
The plugin produces 404 errors when going through page 2, 3, etc.
Is this parameter not handled or does the plugin only rely on default WordPress setting in Reading > Posts per page ?

**Comment by lesterchan** [comment]
You need to pass the query the query to the plugin. See http://scribu.net/wordpress/wp-pagenavi/wpn-2-74.html
